### ISSUE TITLE
Question: How to set the Pfx password?

### ISSUE THREAD

**Issue by nicolassaleron** [HodorNV/ALOps#11]
Hello,

I would like testing the command "ALOpsAppSign" but I cannot find how to set the password of the PFX file.

**Comment by AdminHodor** [comment]
Hello,

Good point, the password variable for this step is done via the environment variables instead of parameters. This is also the reason it is missing in the documentation. 

Example of how it should work in the current release, note our example uses linked variables.

- task: ALOpsAppSign@1
  displayName: 'ALOPS App Sign'
  env:
    pfx_password: $(alops_pfx_password)
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'
    pfx_path: $(PFXFile)

We will change this behaviour for the next release (very soon), the "pfx_password" variable will move to inputs where it belongs anyway. The next one or two releases will support both parameters, afterwards we will remove the environment variable.

Please let us know if this information is sufficient.

Kind regards,

**Comment by nicolassaleron** [comment]
Yes, thank you for the example, it works fine now
