### ISSUE TITLE
Issue during compiling on V16

### ISSUE THREAD

**Issue by nixpt82** [HodorNV/ALOps#113]
Hi guys,

When i try to complile a simple app to the new version in a a docker container, seems the compiler doesnt work causing a error. 

I attached the log.

[6_ALOps App Compiler.txt](https://github.com/HodorNV/ALOps/files/4493063/6_ALOps.App.Compiler.txt)

Thanks

**Comment by AdminHodor** [comment]
Dear @nixpt82 ,

The error seems to be with executing the "alc.exe" command:  "AL Compiler Exit Code: -1073741502".
Very likely this is due to configuration of the Docker host, Vsts Agent, etc...

Could you please elaborate on how the job is run?
  - Vsts Agent Version ?  x86 or x64 ?  (Has to be 64x)
  - Windows version of the Docker host ?  (Windows 10 is not supported)

It's recommended to run the DevOps agent/ Docker host on a Windows Server platform, atleast version 2016, best 2019. 

Kind regards,

**Comment by nixpt82** [comment]
Hi @AdminHodor, 

Vsts Agent Version is a x64 and is running on a Docker host server 2019 on D4s v3.

Im not sure if this is related with hyper-v isolation, in the same configuration i was able to compile with a BC15.2 docker image.

Kind Regards,

**Comment by nixpt82** [comment]
Hyper-v isolation fix the issue.
