### ISSUE TITLE
Sometimes ALOpsAppCompiler & ALOpsAppPublish never ends

### ISSUE THREAD

**Issue by nicolassaleron** [HodorNV/ALOps#12]
Hello,

I encounter a problem with ALOpsAppCompiler & ALOpsAppPublish functions.
Sometimes, these functions seem to never catch the fact they have successfuly done their job and the task never ends.

In my project, I have two extensions: one for the app, one for the tests.
So I run ALOpsAppCompiler for app, ALOpsAppPublish for app, then ALOpsAppCompiler for test app, ALOpsAppPublish for test app.

When it succeeds, ALOpsAppCompiler takes about 1 minutes 30 seconds and ALOpsAppPublish  bout 30 seconds.
However, sometimes the task runs during more than 30 minutes... and seems never stopping.
One more thing: it seems that it always fails on the second ALOpsAppCompiler or ALOpsAppPublish call.

**Here is the last outputs for ALOpsAppCompiler when it fails:**

Compilation started for project 'XXX - Test App' containing '13' files at '10:40:30.164'.

Compilation ended at '10:40:38.140'.

##[error]The operation was canceled.
##[section]Async Command Start: Add Build Tag
Build '589' has following tags now: microsoft/bcsandbox-fr-ltsc2019, BC.Platform.14.0.29530.31705, BC.Version.14.0.29537.31808, AL.Compiler.3.0.106655, App.XXX.1.0.201907.0
##[section]Async Command End: Add Build Tag
##[section]Async Command Start: Upload Artifact
Uploading 1 files
File upload succeed.
Upload 'd:\a\1\s\compilelog.txt' to file container: '#/3870860/XXX'
Associated artifact 242 with build 589
##[section]Async Command End: Upload Artifact
##[section]Finishing: ALOpsAppCompiler

**Here is the last outputs for ALOpsAppPublish when it fails:**

*** Sync Tenant default
*** Sync App [XXX - Test App] on tenant [default]
*** Install App [XXX - Test App] on tenant [default]

**************************************

##[error]The operation was canceled.
##[section]Async Command Start: Add Build Tag
Build '588' has following tags now: microsoft/bcsandbox-fr-ltsc2019, BC.Platform.14.0.29530.31705, BC.Version.14.0.29537.31808, AL.Compiler.3.0.106655, App.XXX.1.0.201907.0, App.XXX- Test App.1.0.201907.0
##[section]Async Command End: Add Build Tag
##[section]Finishing: ALOpsAppPublish

_Note : the message "##[error]The operation was canceled." appears when I stop the Build process because I took too long._

**Comment by AdminHodor** [comment]
We have did not yet encounter this problem on our Compilation/Publish steps. We did however ran into a similar problem, but always on the TestSuite step. 

From our experience, hanging steps are mostly caused by resources shortage. 

We run all out Docker-Start steps with 4G memory, the bigger apps or apps with testsuites we run on 8G memory to avoid this.

Also check if the host has enough memory for the container.

If the problem persist, please let us know so we can dig deeper.

**Comment by nicolassaleron** [comment]
It works nice with at least 8G of memory

Thank you!

**Comment by AdminHodor** [comment]
Re-Opening because we are not 100% sure memory was the issue. 

We spotted this "Freeze/Hang" behavior on another environment, where memory certainly is not the issue. 
The task stops outputting any logs, eventually the jobs times-out after an hour. 

The freeze seems to be caused by the VSTS-Agent, DevOps (OnPrem) installation, or a network connection in between. We are able to replicate this behavior with accuracy, so we have something to dig for.

We'll post updates on this thread as soon as we have some solid findings.

**Comment by AdminHodor** [comment]
The problem  was located in how the  VSTS Agent processes the job, on random (1% of builds) occasions  the StandardOutput and StandardError streams seemed to get deadlocked. We found a workaround  that enables us to exit the environment  even when such a deadlock exists. 
The fix is available for all Tasks in ALOps v1.422 (10/07/2019)

A second problem was located in the ALOpsDockerWait tasks, it didn't properly check  the container status and kept running when a container exited on Error. The task is fixed and does check container status. The fix is available in ALOps v1.422 (10/07/2019)
