### ISSUE TITLE
How to copy files to Docker container?

### ISSUE THREAD

**Issue by jcoe-nvt** [HodorNV/ALOps#150]
We recently got a new (faster) server for our build agent and due to this upgrade our existing pipelines started to fail.

We use the 'docker cp' command to import all our dependend apps and dll's to the docker container at once (the apps and dll's aren't part of the repository, but are artifacts that are firstly downloaded).
By adding all the different dll's at once, we don't need to restart the service each time new dll's are imported and thus saving a lot of time.

On the new server we can't use this command anymore as Hyper-V is enabled.
A possible solution is stopping the container, copying the files and then restart the container. 
But we don't like this solution as the restart is adding more time to the build process.

Another solution was trying the Copy-FileToNavContainer of the NavContainerHelper module, but the container can't seem to find the files on the host computer:
![Copy-FileToNavContainer](https://user-images.githubusercontent.com/49404625/87283963-23369500-c4f6-11ea-8d22-98c9a30dda08.png)

Probably because there seem to be no mounts?
![image](https://user-images.githubusercontent.com/49404625/87284316-832d3b80-c4f6-11ea-870b-6b68b1211828.png)

We also tried to mount a volume to the docker container by adding this argument to the docker start cmd:
> -v C:\Users\jcoe\Downloads:C:\jcoe

The docker succesfully started and created a 'jcoe' folder on the docker container, but the folder is empty in the container, while there are files in that folder on the host.

Any suggestions?

**Comment by AdminHodor** [comment]
Dear @jcoe-nvt ,

For the compression we use the default "Compress-Archive" and "Expand-Archive" from Powershell. 
We are aware there are reports about slow performance on these cmdlets in specific Powershell versions.

To mitigate this we could switch to the Dotnet variant for Compression, which should be significantly faster. 
We'll investigate asap and let you know if we can provide this enhancement in the near future.

Kind regards,

**Comment by jcoe-nvt** [comment]
@AdminHodor : Any suggestions how to procceed? This is preventing us to use our new build server.

**Comment by waldo1001** [comment]
Hi,
there are multiple things here: 
- Copy Files to Docker
- Handle Dlls
- Mount a folder

What we plan to do:
- Add an ability in DockerStart step to copy files from folder to folder within Docker.  This way, we're able to do that before the server start, which is much more performant in the long run.
- Create a new step (which you shouldn't need anymore): CopyFilesToDocker

Did you download the files to the defaultworkingfolder?  Because the DockerStart will always copy all files to the container (c:\Run\Devops) anyway.  So if you download/copy the files to the DefaultWorkingFolder before you build the container - the files should end up in Docker already...

**Comment by AdminHodor** [comment]
Dear @jcoe-nvt ,

In our latest release (v1.432.1558) there are some new features that will help you out with this. The DevOps workingfolder is scanned for DLL's, every folder containing DLL's is than copied to the container during "ALOpsDockerStart" before the container is actually started. This avoids the need for restarting the Service.

At the end of the ALOpsDockerWait step, we still copy all files from the workingfolder to the container. Here we made a change using dotnet ZIP instead of Powershell due to performance issues with the powershell ZIP.

Could you please check if this enhancement is working for you? The log for this DLL copy action can be found in the "ALOpsDockerStart" step between the two (blue) docker commands.

```
*** Checking for Assemblies in App
*** Create TempFile
*** Test Docker-Path: [/Program Files/Microsoft Dynamics NAV/160/Service/Add-ins/]
*** Cleanup TempFile
*** BC Service Folder: [/Program Files/Microsoft Dynamics NAV/160/Service/Add-ins/]
*** Assemblies in App found. Adding Probing Paths (1).
  * C:\vsts-agent-onpremise\_work\40\s\AddIns
##[command]"docker" start bb71e09ae4abbf0f29f4c18970df8bf5df3a6c520ce73384eaf4ab8dd29d0123
```

Kind regards,

**Comment by jcoe-nvt** [comment]
@AdminHodor,
Thx for providing this new feature. I can now remove my custom code to move dll's/artifatcs to the docker container and just rely on the logic you are providing.
