### ISSUE TITLE
Question/Request: Update version number (in app.json)

### ISSUE THREAD

**Issue by peterz84** [HodorNV/ALOps#196]
Problem: our developers develop locally and compile against a local installation of BC (or Docker). The version in our app.json is always 1.0.0.0. When we have a succesfull build and release from devops, our testenvironment is updated and has for example version 1.0.0.19888.

Sometimes the developers want an updated database with current data. They want a copy of test locally. But hence the problem with compiling now: version 1.0.0.0 gives me an error about a new version installed already.

Is it possible to update the version number in app.json's as well after a succesfull build? So the version is always up to date with the newest build? The Update Build Number option in the Compile step seems not to change the build number in the repo, only in the compiled app's.

**Comment by waldo1001** [comment]
Well .. you can do that, indeed.  We don't do that, so I don't have the exact code, but it's pretty similar to something else we do.  Let me draw the picture:

in our "NextMajor" builds, we always want to update our branch from master - also these are merely a bunch of git commands as well - like a `git commit` would be.. .  This is what we use for that:

```yaml
- powershell: |
   $env:GIT_REDIRECT_STDERR = '2>&1' # Do not report git output as error... However error is also only text now
   
   git checkout master
   git pull origin master
   git checkout $env:branch_name
   git fetch
   git pull
   git pull origin master
   git push
  env:
    branch_name: '${{ parameters.branch_name }}'
  displayName: 'Update Branch From Master'
```

But ...

I'm wondering what impact this will have on your CI builds, since you'd change the master-branch, it's going to trigger another build - so in a way, you might be triggering an endless loop here...

**Comment by peterz84** [comment]
That would be rather difficult to achieve (for me at least) I think, because it has to update the app.json (version no) but also the dependancies. I hoped for a (existing) compile task feature in ALOPS.

For the endless loop problem a solution could be to implement a commit description with ***NO_CI***.

**Comment by waldo1001** [comment]
It's easier than you think.  You don't have to mess around with the app.json.  ALOps is already updating the app.json when compiling.  It's just a matter of committing that file after the compile-step.  It's litterally what I just sent, only not the scripts.  I suppose it's a "git commit" that you need.. .

For ALOps to call these git commands - I don't know.  In my opinion, it's bad practice to update a stable branch of the code during a (CI) build.  So facilitating that - I have some mixed feelings for that. 🤔  Especially because I expect a lot of unexpected behaviour, and therefor also support that will follow on that.

Now, that being said - we have the same issue, and our developers basically just set their app.json manually (without committing it to the repo).

Now that I think about it - just from the top of my head - what if:
- in case your build app version would be 4.x
- then set your app.json in the repo to 5.x
- hardcode the version in ALOps to 4.x
this way, the compile is always correct, and the build is always lower.. .

**Comment by waldo1001** [comment]
Hi @peterz84 , did you try what I suggested above?

**Comment by peterz84** [comment]
@waldo1001 not yet (don't know where to find the time), but it seems a good solution.
