### ISSUE TITLE
Propose Library Variable Storage by default when enabling 'Install AL TestTool'

### ISSUE THREAD

**Issue by fvet** [HodorNV/ALOps#230]
**Is your feature request related to a problem? Please describe.**

Would it be possible to automatically include ' Library Variable Storage' as AL App to Install when enabling 'Install AL TestTool' in a CD pipeline?

![image](https://user-images.githubusercontent.com/25268332/96896652-0e22b800-148e-11eb-88a9-81bb0967a05b.png)

_Might be irrelevant if the step is only applicable to v15 ..._

**Comment by waldo1001** [comment]
Well, what can I say.  I blame the confusion to Microsoft (do know that they will again change this in the future)... .

We try to make it work for everyone:
there are customers with pipelines that are not on v17, so "just" take the v17 settings would break a lot.  So we chose to take all apps as known until v16, and add the "variable storage" in v17 in the background if ALOps detects it's a v17.. .

I understand it's confusing .. but this makes less breaking changes for everyone who is using ALOps, I guess, no?

The DockerCreate-step is a wrapper for the BcContainerHelper.  So we are a bit dependent on what Freddy does here.. . but if you "includetesttoolkit", you always ever all.  But for your example, I would switch all to true (since you don't need the tests, only the library and the framework).
