### ISSUE TITLE
Get-BcContainerSharedFolders : The property 'Mounts' cannot be found on this object

### ISSUE THREAD

**Issue by fvet** [HodorNV/ALOps#293]
**Describe the bug**
Following https://github.com/microsoft/navcontainerhelper/issues/1592, it seems like we cannot use the native Get-BcContainerEventLog on a container created by ALOps, due to the lack of 'mounts' / shares.

**Expected behavior**
Would be nice if we could call BcContainerEventLog on a container created by ALOps (by adding the required shares that are included in case a default New-BCContainer is created).

**Comment by waldo1001** [comment]
It's not a bug, it's by design.

It's a bit difficult to explain, but let me try.  Working with "mounts" is actually not the best practice in a DevOps Agent environment.  Every job needs to have an isolated environment, while we noticed (at least way back in time) that the way BcContainerHelper does it, it leaves traces from previous builds / and even reuses the same mounts (depending on the pipelines/names and such).  Now just imagine you have multiple agents on one machine (which many have).  This might lead to wrong conclusions, locked files/folders, inconsistent output/crashes, .. .  That's why ALOps is copying the files to the container rather than working with "mounts".. .

It's pretty easy to check the event log - Get-EventLog in PowerShell on a remote session in the container gives you the output.  

We could do a few things: 
- foresee a set of scripts you can use to check "different" things
- foresee a step (devops) that displays the eventlog with filter-abilities
- ...

you have other ideas?

**Comment by waldo1001** [comment]
Plan:
We'll create a parameter "SaveEventLog" in the DockerRemove and make the logs part of the artifacts.

**Comment by AdminHodor** [comment]
Dear @fvet ,

Could you please check this in our latest release v1.438 ?
We have to option to export EventLogs from the container in the ALOpsDockerRemove step.

Kind regards
