### ISSUE TITLE
Performance Tools kit run with Alops Task

### ISSUE THREAD

**Issue by ccourvoisier** [HodorNV/ALOps#392]
**Is your feature request related to a problem? Please describe.**
not related to an issue, it's more an improvement

**Describe the solution you'd like**
Create a specific Alops task in order to be able to run performance test on a sandbox through pipeline and get the result on Devops.

**Describe alternatives you've considered**
I will try to do that with powershell but I'm used to have wonderfull feature from Alops :)

**Additional context**

**Comment by waldo1001** [comment]
This is indeed on the roadmap :-).  

Can you give us more feedback on what you would like to see in this step?  Like:
- how to set up the suite (I think that should be done outside of ALOps with an install-codeunit)
- what params?
- output?
- ...

**Comment by titofffffff** [comment]
@waldo1001 : on my side at this stage I just want to be able to run a specific test suite on a Sandbox (not a docker container because I don't think it will be relevant).

My plan is : 
create one or several Performance Suite with customized scenario
run these suite on a specific BC Sandbox everyday using pipeline. This sandbox will have also all my customer extension (it will be a part of delivery pipeline).
Get and track performance result using PBI or Telemetry
Set an automated alert if we have a degradation of the performance of test scenario

**Comment by waldo1001** [comment]
And how do you want to get the results in PowerBI/Telemetry?

**Comment by titofffffff** [comment]
**Telemetry** : I will have customized performance test scenario, I think to build a specific process in order to push result on telemetry, Alops not needed
**Power Bi** : publish the related page simply, Alops not needed
**Other** : it could be good to have the result on Devops as test result : Alops is very welcome !

**Comment by waldo1001** [comment]
I think it would be rather simple to make the result available in a few ways .. let's investigate..

**Comment by ccourvoisier** [comment]
@waldo1001, any update around this point ? Is it finally on your roadmap ? Any timeline on your side ?

**Comment by NAVFreak** [comment]
@AdminHodor I'm also eager for this as mentioned on Techdays 😁

**Comment by waldo1001** [comment]
Sorry, v21 broke quite some things (including externaldeployer) which we are fixing now.. .  This will have to wait .. :(

**Comment by NAVFreak** [comment]
Externaldeployer 😱

**Comment by CarloAxians** [comment]
Hi @waldo1001, Any update on this? Is it still on the roadmap?

**Comment by waldo1001** [comment]
Documentation (example pipeline) is upcoming.

You'll be able to find documentation here:
https://docs.alops.be/ALOpsSteps/Buildstepsv1/#alops_bcpt_run
