### ISSUE TITLE
Restart loop occurs sometimes

### ISSUE THREAD

**Issue by PatrickGrabensteiner** [HodorNV/ALOps#44]
Sometimes the container is not initialized correctly, then it stucks in a Restart loop

![image](https://user-images.githubusercontent.com/35697862/67747097-4e408d80-fa28-11e9-90ce-01380b8f6579.png)

**Comment by waldo1001** [comment]
We will need more information.  

The docker-part is purely dependent from your dockerhost and the containers from Microsoft .. we don't do anything (that I know) with the Docker-part.  This is a first to me as well.

So - may be the yaml, the specific docker image?

**Comment by waldo1001** [comment]
It's on the list!

**Comment by AdminHodor** [comment]
The "error string" Is included in the next release v1.426 which will be made available this week.

Is there a reason for having the "container_restart: always" on the ALOpsDockerStart step? This will induce the restart behavior instead of stopping the container. With the default restart behavior "no" the container would exit on this error which is picked up by ALOpsDockerWait.

**Comment by AdminHodor** [comment]
Hello @PatrickGrabensteiner ,

Did the new release mitigate the restart loop? We'll keep the issue open until we are sure you are settled.

Kind regards,

Bart Bourgeois
