### ISSUE TITLE
Suggestion: Unzip vsix to Work Folder

### ISSUE THREAD

**Issue by DanielGoehler** [HodorNV/ALOps#447]
**Is your feature request related to a problem? Please describe.**
We have multiple build agents on the same Windows server. This saves us space and a lot of time. But we see the error "Windows PowerShell is in non-interactive mode. The Read and Prompt feature is not available." (#445) very often on some days. If I start the pipeline immediately, it works. 
We have analyzed and suspect it is because at least two pipelines are unpacking the same vsix and the second process may be getting an overwrite dialog or error message. We don't know for sure. 

**Describe the solution you'd like**
If there was an option to unpack the Vsix to the working folder, this error would probably go away.

**Comment by waldo1001** [comment]
Hi @DanielGoehler ,

It's not a good idea to have multiple build agents on one windows server.  It gives unpredictable results.
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser#install

It's best to have multiple small VMs in stead of one VM with multiple agents.

Another solution could be docker (I know Cosmo does that).

**Comment by DanielGoehler** [comment]
Ok, thanks.

**Comment by MattTraxinger** [comment]
In case anyone else comes across this error, we were getting the same thing. We have multiple agents on the same server because it's just better for pipeline speed and cost purposes honestly. But we did start to see the "Windows PowerShell is in non-interactive mode. The Read and Prompt feature is not available." error and we rolled ALOps out across projects. It does appear to be because of a race condition where multiple pipelines need to download the VSIX at the same time.

It's not an ideal solution, but I just added a separate YAML task before and after the compile step. Before, it will see if it has all of the folders it needs to do the compile (VSIX, Platform, etc.). If it doesn't, it will put a "lock file" in that directory and proceed to the compile step where it will get downloaded. It will also check to see if that lock file exists and wait until it is gone, or for a set amount of time. After the compile step it will delete the lock file.

It's quick and dirty but gets the job done the majority of the time.
