### ISSUE TITLE
Use Custom Ruleset for Compiler

### ISSUE THREAD

**Issue by PatrickGrabensteiner** [HodorNV/ALOps#53]
We've downgraded some warnings to info.
If we compile our code with ALOps, a warning will still be issued.
It seems that custom rulesets are not supported.
Please use the rulesets which are in the repository to compile

**Comment by AdminHodor** [comment]
Are you  working with multi-root workspaces, cfr having multiple apps in the same repository?
We notice a possible bug when using this configuration. We'll investigate this scenario asap and keep you posted.

**Comment by PatrickGrabensteiner** [comment]
Yes we're using Multiroot workspaces

**Comment by waldo1001** [comment]
In our internal build the bug is solved - expect a solution soon.
Do know that you explicitly need to set the property "al_analyzer" in the "ALOpsAppCompiler" step.  It will not read the settings from any settings-file.  This is by design (we need to be able to run different pipelines with different contexts)

**Comment by AdminHodor** [comment]
Hello @PatrickGrabensteiner ,

Fix is available in the new version "1.426.946" that we just released. Please it could take a couple of pipeline run for DevOps to pickup the new version. Please let us know if this resolved your issue.

Kind regards,

Bart Bourgeois

**Comment by PatrickGrabensteiner** [comment]
Thanks it's works just fine now :-)
