### ISSUE TITLE
Is it possible to define the artifactName in ALOpstask

### ISSUE THREAD

**Issue by MortenRa** [HodorNV/ALOps#530]
I can not see if there is a parameter for artifactName: as I see it defaults to artifact folder "Dynamics 365" if I set publish_artifact:true

What if we want to split the app file and translation file into 2 separate artifact folders I can not see the option for this.

in ALOpsAppCompiler@2 I have option 
publishxlif: true 

Which put translation file into default folder "Dynamics 365"

I can control the artifact app if I use PublishBuildArtifacts@1 but since I have 
the parameter "publish artifact" in several ALops task it would be great if we can set the artifactName under these task.

is this a feature request or did I missed something.

**Comment by waldo1001** [comment]
First of all - we can't do this from our extension (basically from PowerShell), where we can't execute default DevOps tasks (sounds weird, I know).

But ... you can.  

Few tips:
- use the "AlopsInfo" task to learn about ALL variables you have at your disposal.  
- do NOT publish anything from ALOps-tasks (since ALOps can only publish in one and the same artifact-folder, and you want to split).
- Use the right variables in two PublishBuildArtifacts@1 steps to upload to the corresponding artifacts.. .

Would that be ok for you?

**Comment by MortenRa** [comment]
yep I´ll try to no worries
