### ISSUE TITLE
ALOps AppCompiler will be reconized as Trojan:Script/Wacatac.B!ml

### ISSUE THREAD

**Issue by DanielGoehler** [HodorNV/ALOps#531]
**Describe the bug**
Today Windows Defender reconized the file C:\agent\_work\_tasks\ALOpsAppCompiler_6ccb97e4-cd3b-4f5c-82d0-3b733949d45d\2.0.3024\ps_modules\AppCompiler\210a3946-14f0-4fd9-962b-b513c620288f.ps1 as Trojan:Script/Wacatac.B!ml

Of course, I can create an exception rule for C:\agent in Windows Defender, but the strange feeling remains when I run PowerShell in the context of a local administrator and Windows Defender thinks that this could be a Trojan.

VirusTotal doesn't it is a virus, but there are strage issues (File Written C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\Microsoft\UPnP Device Host\upnphost\udhisapi.dll and access to HKLM\SOFTWARE\Microsoft\Windows Media Player NSS\3.0\Servers\A70D59A1-8EAD-4F40-AAAB-FBFC460800A4\FriendlyName)
<img width="995" alt="Screenshot" src="https://user-images.githubusercontent.com/9556549/173581561-2b75fc36-c7b7-4756-8f0f-3263c2bc10c3.png">

**Comment by waldo1001** [comment]
Thanks for the notification, and the (temporary?) solution.

We have been warning that it might be necessary to put the working-folder of the agent in the exclusion-list of your virusscanners, simply because it's a known concern that ps1-files might be (wrongly) accused by defender to be malicious.. .
I get the concern - but I hope you get that there isn't much we can do about it.  Possibly, any downloaded script is a concern and could be malware - I hope you trust us that it isn't.. :-/.

On top of that: 
A good practice is to NOT run DevOps agents on your network.  We for example particularly have it completely disconnected from any connectivity to anything of our internal systems.  Just because of the concern that is addressed above: you run automated stuff with an admin account.  Anyone who is able to configure/edit/run pipelines, will be able to do whatever they like with that account - scripted.  So be careful, and move your agents out of your internal network!  Infrastructurally, this is not difficult.. .

**Comment by DanielGoehler** [comment]
Hmm, how do you prevent that in case of a build agent infection your artifacts that you distribute more or less automatically to your customers?

Such a build agent looks like a juicy target for malicious people.

**Comment by dsaveyn** [comment]
Our Build Server is an AzureVM that is completely isolated. Windows Defender is however enabled on this machine since we are not allowed to turn it of (internal policy). The Build Agents are now excluded and this works like a charm. 

But - in theory - developers might be able to check-in malicious files. With the Build Agents excluded from Windows Defender this won't be detected and infected app files might be published and distributed. I know this scenario might seem very unlikely... but... Just some fuelfor thought I guess. For

**Comment by waldo1001** [comment]
It is absolutely something that is on our minds.  But to fix that, we need to move away from PowerShell.  Believe it or not .. that process is in place (yes, we're moving to .Net) - but it's a major shift that needs a lot of time, test and approval - and some cooperations from Microsoft.  Some day, we'll come out with (what we call) ALOpsV3.  This will mitigate many PowerShell limitations that we're suffering at the moment .. .

But for now .. it is what it is, I'm afraid.

**Comment by DanielGoehler** [comment]
@waldo1001 With AV disabled, yes.

**Comment by dsaveyn** [comment]
> @dsaveyn , @DanielGoehler , @fvet,
> 
> Were you all able to resolve the issue?

I excluded the folder with all our Build Agents from Windows Defender and no issues anymore:) works like a charm.
