### ISSUE TITLE
Error when using the ALOps.ExternalDeployer

### ISSUE THREAD

**Issue by panas78** [HodorNV/ALOps#553]
When Trying to use the ALOps.ExternalDeployer to publish a custom "Base" extension from Page 2507 i get the following error

Could not find file 'C:\Program Files\WindowsPowerShell\Modules\ALOps.ExternalDeployer\1.38\bin\db\00000000-0000-0000-0000-000000000000.json'.

![Screenshot 2022-08-12 201037](https://user-images.githubusercontent.com/64047553/184409259-9c110baa-2bb8-495a-8d0b-1d1b7288f3c3.png)

**Comment by waldo1001** [comment]
I just got feedback for the developer that this can happen when you opened this page when the job wasn't done yet.  Don't open the status-page when the job is still running, because when you do, it will try to find the feedback (which is in a json), but since the job is not done yet, it will fail - and even fail the job along the way.

So: deploy, wait for the feedback, if failed or succeeded, only THEN open the page.

**Comment by waldo1001** [comment]
@panas78 , can you give feedback on the above?  We're pretty sure that it's the "opening of the deployment status page" that caused this ..

**Comment by panas78** [comment]
@waldo1001 You are probably right regarding the page open. It was a rather big app . When i left it do its thing without open the status page the deployment completed successfully
