### ISSUE TITLE
ALOps.ExternalDeployer: Deployment failed if BC deployUser license type is 'Application' or 'External Admisnitrator'

### ISSUE THREAD

**Issue by jithendra415** [HodorNV/ALOps#566]
Since a few days, we are facing problems with Deployments when Deploy User's license type is 'Application' or 'External Administrator'. Its working fine if the license type is 'Full User', but that costs a license for customers. Even the 'External Administrator' license type is costing a license for the customer. 

Error: 
##[error]Exception in BCConnector.GetAPIData: Unable to connect to the remote server
*** Selected Company:  []
##[error]Cannot find an overload for "GetExtensions" and the argument count: "1".

**Expected behavior**
Extensions were successfully deployed only when the Deploy User's license type is 'Full user'. Expected behavior is that it should also work for Application or External Administrator, right? And also, unlike 'Application', 'why the 'External Administrator' license type costing a license?
![image](https://user-images.githubusercontent.com/61264260/190398528-d15c3706-682b-41bb-ad05-0006fa049d5f.png)

Let us know what could cause the difference from the past. 

Thanks & Regards
Jitendra 
(jkarri@mprise.nl)

**Comment by waldo1001** [comment]
I fail to see how is this an ALOps issue.  BC licensing is not something we can influence.

Some background info: ALOps.ExternalDeployer enables the ability to use the AutomationAPI in an OnPrem environment.  So: uploading to the "Upload"-table through the automation-api by setting a setting on the customSettings.config on server-level, which would call an api to upload the extension through powershell.

Your problem is even with the "GetExtensions"-call, which merely is a call to get all extensions (GET-method).  Not even an upload of the extension.

If Microsoft decides that you don't have access to the automation-api with certain license types - then our hands are tied 🤷‍♂️. 

Can you try postman-calls to the getextensions with the same credentials?

**Comment by waldo1001** [comment]
Tip from development: can you try with "External User"?

Also, it says: "unable to connect" - we don't see the detailed log, but please also check the urls as we suspect it's not even able to reach the endpoint .. .

**Comment by jithendra415** [comment]
We getting this error when we not use Full user license type. Let me check with external user and get back to you..

**Comment by jithendra415** [comment]
"External User" license type worked for us. And it also not costing a BC license for the customer. Thank you @waldo1001
