### ISSUE TITLE
ALOps Import FOB Issue

### ISSUE THREAD

**Issue by titofffffff** [HodorNV/ALOps#58]
hello,

I try to build a pipeline on NAV2018 (container 'microsoft/dynamics-nav:2018-cu9-fr')

I have an issue when I try to import a fob file.
here below the result : 
![image](https://user-images.githubusercontent.com/5903546/70270297-61bbe280-17a4-11ea-8ffd-5061cc33e969.png)

**Comment by AdminHodor** [comment]
Hello @titofffffff ,

We updated the code to be compatible with NAV2018 for this this. The fix is included in our new release v1.426.960, released today. Please note it could take a couple of pipeline runs for DevOps to pickup the updated task.

Please let Us know if this resolved your issue.

Kind regards

**Comment by titofffffff** [comment]
hello,

it's ok
thanks for this quick fix
