### ISSUE TITLE
Problems with permission set

### ISSUE THREAD

**Issue by NAVFreak** [HodorNV/ALOps#595]
**Is your feature request related to a problem? Please describe.**
Is it only we that have the problem that when we merge with pipelines we get permission set errors ??
We have made a permission set in the feature branch, it works all well until we run the final merge pipeline. Then it goes bananas :(
![image](https://user-images.githubusercontent.com/34970096/208675887-fb600a50-e4bf-431d-8298-53e4facabd78.png)

Sometimes we also get a lot of merge conflicts between master/feature/dev branch with the permission set file.

**Describe the solution you'd like**
It would have been so nice if ALOps could generete a permission set file for all objects during compilation. When we didn't have do all these merge conflicts och failing pipelines.

**Describe alternatives you've considered**
Alternative you give us suggestions on how to handle this better than we do today.

**Comment by waldo1001** [comment]
My opinion: 
the source of your problem is the one function Microsoft should never have created: the "generate Permission Set" command in VSCode.  This only creates and updates one file, which causes conflicts.

ALOps generating this file is not an option. We can't use the VSCode-command, so it would imply we create our own version of the file.

The only thing I can recommand is to NOT use that command, and implement a decent permissionset-methodology, like:
- always create an ADMIN and READONLY permissionset for all tables
- split permissionsets for functional area (possibly multiple per app)
- never add permissions for anything other than TableData
- add your "ADMIN" permission Sets to the "D365 Full Access" with a permissionsetextension
- add your "READONLY" permissionset to whatever fits the functionality

Just a suggestion, of course.

This isn't an ALOps issue imho, so I'll close this issue.

**Comment by NAVFreak** [comment]
Thanks for the input!
