### ISSUE TITLE
How to use ForceSync for OnPrem

### ISSUE THREAD

**Issue by Athystrup** [HodorNV/ALOps#624]
Hi 

Do you have an example of how the DEV-endpoint should look, when using the new "DEV Schema Sync Mode" in the ALOps Extension API task?

We are using <Base URL>:<DeveloperServicesPort>/<Server Instance/dev

However this does not seem to work, as we get the following error:

![image](https://user-images.githubusercontent.com/33824984/229081295-5e243bb6-9cf3-4c22-991a-2bcea4d47dca.png)

**Comment by AdminHodor** [comment]
Dear @Athystrup ,

Could you please provide extra details/pipeline logs.
The "Unauthorized" would mean you have an error in the setup of the Credentials, please check if the correct authenticatie schema is selected and the Username/Password are correct.

Kind regards,

**Comment by ryordanov91** [comment]
Hi guys, 

I'm having the same issue. I have double-checked the credentials and they are correct. I'm able to publish from VS Code and Powershell apps with the same credentials, but my release pipeline is failing with the error unauthorized. I can see that the pipeline is accessing the Business Central service because it lists the installed apps in the environment. But when it tries to publish the app file it fails. The error is unrelated to the syncMode option - I get it with forceSync and synchronize. I have also tried with different authentication types - username/password and basic, but it's not working. It is possible that I'm doing something wrong, but I can't figure it out at the moment.  

Just for clarity in my case, the on-prem environment is a local container.

I have attached my log file.

[logs.txt](https://github.com/HodorNV/ALOps/files/11190521/logs.txt)

**Comment by AdminHodor** [comment]
Dear @Athystrup , @ryordanov91, @TheDoubleH,

Please try our latest version v1.455.3607, we hotfixed the Authentication issue for DevPort deploy.

Kind regards,

**Comment by Athystrup** [comment]
@AdminHodor thank you for looking into the issue. 

I have tried with version v1.455.3607 and unfortunately I get the exact same error as before. My log contains some sensitive information, so I will see if I can clean it, but it basically looks almost identical to the one provided by @ryordanov91.

**Comment by AdminHodor** [comment]
Dear @Athystrup ,

If you want to keep the logs of github, you are always free to email it to admin@hodor.be. 
We handle all private info with care.

Kind regards,

**Comment by Athystrup** [comment]
@AdminHodor I have sent you an email.

**Comment by Athystrup** [comment]
@AdminHodor Anything new regarding this issue?

**Comment by waldo1001** [comment]
We have problems in replicating the issue.  We try, but it keeps succeeding :-/.

When we see this:  `Publishing to http://buildenv:7049/bc/dev/apps?SchemaUpdateMode=forcesync`
what we notice:
- http, no https
- no fqdm
- is it some kind of local docker setup?
- ...

Do you think it's possible to set up the service with best practices in mind? 

In the meantime, we'll add some more logging, because we need to know exactly which URL it's using, and which authentication, before we can say anything more.. .

**Comment by Athystrup** [comment]
@waldo1001 

After looking through the Powershell task, I think that I might have found the issue. It seems that the credentials are not correctly added to the header when using the dev endpoint.

 I have sent an email to @AdminHodor which describes the Powershell change that helped solve the issue for me. 
 
 Let me know if this information was helpful to you.

**Comment by waldo1001** [comment]
Thanks - we'll look into it!
should be fixed in next release!

**Comment by waldo1001** [comment]
Will be available in the upcoming release.  Today or tomorrow.
