### ISSUE TITLE
AppLicenseCheck: Speed up?

### ISSUE THREAD

**Issue by DanielGoehler** [HodorNV/ALOps#809]
**Is your feature request related to a problem? Please describe.**
The AppLicenseCheck currently consumes around 2:30 minutes of pipeline runtime, even though the actual license check of modules only takes about 8 seconds. Is there a way to speed up the preceding steps, such as downloading and extracting artifacts before the step importing BCLicenseReader? We have already installed 7zip on all agent hosts.

**Comment by waldo1001** [comment]
The time loss is because we need the artifact for the dlls (most of the time gets consumed by the download of the artifact).  That's why we take a "weekly" .. so you'd only have this time loss once a week.

Except you're using some kind of temp agents or cleanup the agent too eagerly...

Can you try to check to reuse the same artifact?

We'll see if we can reuse another step's artifacts (like the compilerv2)

**Comment by DanielGoehler** [comment]
Thank you! By reusing the artifact, the time reduces just 1 minute. Nice.
